//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickbooksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string AccountType { get; set; }
        public string Classification { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public string SyncToken { get; set; }
    }
}
