//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickbooksApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string RealmId { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> AccessTokenExpiresIn { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpiresIn { get; set; }
    }
}
