//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickbooksDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceInfo
    {
        public string Id { get; set; }
        public Nullable<double> TotalAmt { get; set; }
        public string SyncToken { get; set; }
        public string CustomerId { get; set; }
        public string TxnDate { get; set; }
    }
}
