//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickbooksDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorInfo
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<double> Balance { get; set; }
        public string SyncToken { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
